#ifndef __keymacros_h
#define __keymacros_h

#include "layers.h"
#include "anvil_map.h"
#include "adb_keys.h"
#include "adb_scripts.h"

enum custom_keycodes {
    // DOTA_TYPE_ITEM = SAFE_RANGE,
    RASPBERRY_01 = SAFE_RANGE,
    RASPBERRY_02,
    RASPBERRY_03,
    RASPBERRY_04,
    RASPBERRY_05,
    RASPBERRY_06,
    RASPBERRY_07,
    RASPBERRY_08,
    RASPBERRY_09,
    RASPBERRY_10,
    RASPBERRY_11,
    RASPBERRY_12,
    RASPBERRY_13,
    RASPBERRY_14,
    RASPBERRY_15,
    RASPBERRY_16,
    RASPBERRY_17,
    RASPBERRY_18,
    RASPBERRY_19,
    RASPBERRY_20,
    RASPBERRY_21,
    RASPBERRY_22,
    RASPBERRY_23,
    RASPBERRY_24,
    RASPBERRY_25,
    RASPBERRY_26,
    RASPBERRY_27,
    RASPBERRY_28,
    RASPBERRY_29,
    RASPBERRY_30,
    RASPBERRY_31,
    RASPBERRY_32,
    RASPBERRY_33,
    RASPBERRY_34,
    RASPBERRY_35,
    RASPBERRY_36,
    RASPBERRY_37,
    RASPBERRY_38,
    RASPBERRY_39,
    DEMO_01,
    DEMO_02,
    DEMO_03,
    DEMO_04,
    DEMO_05,
    DEMO_06,
    DEMO_07,
    DEMO_08,
    DEMO_09,
    DEMO_10,
    DEMO_11,
    DEMO_12,
    DEMO_13,
    DEMO_14,
    DEMO_15,
    DEMO_16,
    DEMO_17,
    DEMO_18,
    DEMO_19,
    DEMO_20,
    DEMO_21,
    DEMO_22,
    DEMO_23,
    DEMO_24,
    DEMO_25,
    DEMO_26,
    DEMO_27,
    DEMO_28,
    DEMO_29,
    DEMO_30,
    DEMO_31,
    DEMO_32,
    DEMO_33,
    DEMO_34,
    DEMO_35,
    DEMO_36,
    DEMO_37,
    DEMO_38,
    DEMO_39,
    DEMO_LYR,
    DEMO_ENC_B,
    DEMO_ENC_C,
    DEMO_ENC_D,
    DEMO_RGB_E,
    DEMO_RGB_F,
    DEMO_RGB_G,
    DEMO_H,
    DEMO_I,
    DEMO_J,
    DEMO_K,
    DEMO_L,
    DEMO_M,
    DEMO_N,
    DEMO_O,
    DEMO_P,
    DEMO_Q,
    DEMO_R,
    DEMO_S,
    DEMO_T,
    DEMO_U,
    DEMO_V,
    DEMO_W,
    DEMO_X,
    DEMO_Y,
    DEMO_Z,
    DEMO_1,
    DEMO_2,
    DEMO_3,
    DEMO_4,
    DEMO_5,
    DEMO_6,
    ANVIL_LYR,
    SCREEN_ON,
    SCREEN_OFF,
};

#include "layer_demo.h"
// #include "layer_dota.h"
#include "layer_raspberry.h"
#include "layer_android.h"
#include "layer_scripts.h"
#include "layer_hover.h"

#endif
